Traceback (most recent call last):
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tuppel = (5, 6, 7, "Hoppsann", 8)
print(tuppel, "er en tuppel.")
print("I motsetning til en liste, er det ikke mulig Ã¥ endre verdiene i en tuppel.")
print("Den neste linja vil derfor gi en feilmelding")
tuppel[3] = "Heisann"

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [7][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mI motsetning til en liste, er det ikke mulig Ã¥ endre verdiene i en tuppel.[39m[38;5;124m"[39m)
[1;32m      4[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mDen neste linja vil derfor gi en feilmelding[39m[38;5;124m"[39m)
[0;32m----> 5[0m tuppel[[38;5;241m3[39m] [38;5;241m=[39m [38;5;124m"[39m[38;5;124mHeisann[39m[38;5;124m"[39m

[0;31mTypeError[0m: 'tuple' object does not support item assignment
TypeError: 'tuple' object does not support item assignment

